command: command_word command_body

?command_word: "!" WORD
command_body: (list | value | named_parameter)+

named_parameter: WORD ":" (list | value)

list: "[" [value ("," value)*] "]"

?value: NUMBER | WORD | STRING



// imports from terminal library
%import common.INT              -> NUMBER
%import common.WORD             
%import common.ESCAPED_STRING   -> STRING

// Disregard spaces in text
%ignore " "