from lark import Lark
from lark import exceptions
from lark import Transformer


def build_grammar():
    with open("command_grammar.lark", "r") as file:
        return Lark(file.read(), start="command")


class Add:
    def __init__(self, args):
        self.value = args[0]

    def __str__(self):
        return "Add(%s)" % self.value

    def __repr__(self):
        return self.__str__()


class Sub:
    def __init__(self, args):
        self.value = args[0]

    def __str__(self):
        return "Sub(%s)" % self.value

    def __repr__(self):
        return self.__str__()


# Transforms the tree generated by lark into what we actually want
class CommandTransformer(Transformer):
    def STRING(self, s):
        return s[1:-1]

    def command(self, args):
        return args

    def named_parameter(self, args):
        return (args[0], args[1:])

    def wstring(self, args):
        return args[0].value

    plus_value = Add
    minus_value = Sub

    list = list
    command_body = list
    WORD = str
    NUMBER = int


command_grammar = build_grammar()
command_transformer = CommandTransformer(visit_tokens=True)

parse = command_grammar.parse
transform = command_transformer.transform
