from lark import Lark
from lark import exceptions
from lark import Transformer
import os


def build_grammar():
    grammar_file = os.path.join(os.path.dirname(__file__), "command_grammar.lark")

    with open(grammar_file, "r") as file:
        return Lark(file.read(), start="command")


class Add:
    def __init__(self, args):
        self.value = args

    def __str__(self):
        return "Add(%s)" % self.value

    def __repr__(self):
        return self.__str__()

    def __eq__(self, obj):
        return isinstance(obj, Add) and obj.value == self.value


class Sub:
    def __init__(self, args):
        self.value = args

    def __str__(self):
        return "Sub(%s)" % self.value

    def __repr__(self):
        return self.__str__()

    def __eq__(self, obj):
        return isinstance(obj, Sub) and obj.value == self.value


# Transforms the tree generated by lark into what we actually want
class CommandTransformer(Transformer):
    def STRING(self, s):
        return s[1:-1]

    def command(self, args):
        return args

    def named_parameter(self, args):
        return (args[0], args[1:])

    def wstring(self, args):
        return args[0].value

    def plus_value(self, args):
        return Add(args[0])

    def minus_value(self, args):
        return Sub(args[0])

    list = list
    command_body = list
    WORD = str
    NUMBER = int


command_grammar = build_grammar()
command_transformer = CommandTransformer(visit_tokens=True)

parse = command_grammar.parse
transform = command_transformer.transform
